<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Johnny MyungWon Lee (Modified from Debby Lipschutz &amp; Stuart McGurnaghan)">
<meta name="dcterms.date" content="2023-01-27">
<title>Lab 3 : Logistic Regression and Predictive Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/clipboard/clipboard.min.js"></script>
<script src="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/quarto-html/quarto.js"></script>
<script src="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/quarto-html/popper.min.js"></script>
<script src="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/quarto-html/anchor.min.js"></script>
<link href="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script src="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/kePrint-0.0.1/kePrint.js"></script><link href="Lab_3_Logistic_Regression_and_Predictive_Models_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#logistic-regression" id="toc-logistic-regression" class="nav-link active" data-scroll-target="#logistic-regression">1. Logistic regression</a>
  <ul class="collapse">
<li><a href="#exercise-1.1" id="toc-exercise-1.1" class="nav-link" data-scroll-target="#exercise-1.1">Exercise 1.1</a></li>
  </ul>
</li>
  <li>
<a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation">2. Model evaluation</a>
  <ul class="collapse">
<li><a href="#exercise-2.1" id="toc-exercise-2.1" class="nav-link" data-scroll-target="#exercise-2.1">Exercise 2.1</a></li>
  </ul>
</li>
  <li>
<a href="#making-predictions" id="toc-making-predictions" class="nav-link" data-scroll-target="#making-predictions">3. Making predictions</a>
  <ul class="collapse">
<li><a href="#exercise-3.1" id="toc-exercise-3.1" class="nav-link" data-scroll-target="#exercise-3.1">Exercise 3.1</a></li>
  <li>
<a href="#roc-curves" id="toc-roc-curves" class="nav-link" data-scroll-target="#roc-curves">3.1 ROC curves</a>
  <ul class="collapse">
<li><a href="#exercise-3.2" id="toc-exercise-3.2" class="nav-link" data-scroll-target="#exercise-3.2">Exercise 3.2</a></li>
  <li><a href="#exercise-3.3" id="toc-exercise-3.3" class="nav-link" data-scroll-target="#exercise-3.3">Exercise 3.3</a></li>
  </ul>
</li>
  <li>
<a href="#data-partitioning-and-cross-validation" id="toc-data-partitioning-and-cross-validation" class="nav-link" data-scroll-target="#data-partitioning-and-cross-validation">3.2 Data partitioning and cross-validation</a>
  <ul class="collapse">
<li><a href="#exercise-3.4" id="toc-exercise-3.4" class="nav-link" data-scroll-target="#exercise-3.4">Exercise 3.4</a></li>
  <li><a href="#exercise-3.5" id="toc-exercise-3.5" class="nav-link" data-scroll-target="#exercise-3.5">Exercise 3.5</a></li>
  <li><a href="#exercise-3.6" id="toc-exercise-3.6" class="nav-link" data-scroll-target="#exercise-3.6">Exercise 3.6</a></li>
  </ul>
</li>
  </ul>
</li>
  </ul></nav>
</div>
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Lab 3 : Logistic Regression and Predictive Models</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Johnny MyungWon Lee (Modified from Debby Lipschutz &amp; Stuart McGurnaghan) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 27, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header><section id="logistic-regression" class="level1"><h1>1. Logistic regression</h1>
<p>Generalised Linear Models (GLM) assume that the observed outcome has been drawn from a distribution from the exponential family and that there is a linear relationships between the predictors and (a function of) the mean of that distribution. It is particularly useful with data for which we are unlikely to obtain normally distributed errors such as binary and count data. Medical data is often binary, classifying people as either having a condition (cases) or not (controls). Such binary case-control data can then be used to investigate potential risk/protective factors associated with cases/controls and make predictions. Using a GLM it is assumed that cases and controls were drawn from a binomial distribution and that the logit of the probabilities from the binomial distribution has a linear relationship with the predictors, i.e.&nbsp;<span class="math inline">\(\ln(p/1-p) = X\beta\)</span> with <span class="math inline">\(y\sim Bin(n,p)\)</span>.</p>
<p>Let us consider a case-control study which includes <span class="math inline">\(1327\)</span> women aged <span class="math inline">\(50–81\)</span> with hip fractures as well as <span class="math inline">\(3262\)</span> randomly selected women in the same age range. Among the cases, <span class="math inline">\(40\)</span> women take hormone replacement therapy (HRT); among the controls, <span class="math inline">\(239\)</span> women do. You are interested in finding out whether taking HRT affects the probability of having a hip fracture.</p>
<p>Let us say the only data you have are these summary statistics. You can resolve this (under the assumption a GLM indeed describes the data) by creating a synthetic dataset which has the same characteristics and use that perform your analyses.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">1327</span>),<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">3262</span>)) <span class="co"># cases, controls</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>hrt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">40</span>),<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">1287</span>), <span class="co"># HRT, no HRT in cases</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>        <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">239</span>),<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">3023</span>)) <span class="co"># HRT, no HRT in controls</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To fit a logistic regression model, we can use the generalised linear model function <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code>. For data drawn from a binomial distribution with a logit function linking to the linear predictor, use the option <code>family=binomial(link = "logit")</code>. The logit link function is the standard option for the binomial family and therefore <code>family="binomial"</code> can also be entered instead but we will use the full version for clarity.</p>
<p>Note that if nothing is specified for the family option a Gaussian family with the identity link function is used as standard, which is equivalent to fitting a linear regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>regr.hrt <span class="ot">&lt;-</span><span class="fu">glm</span>(y <span class="sc">~</span> hrt, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span><span class="st">"logit"</span>)) </span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">summary</span>(regr.hrt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ hrt, family = binomial(link = "logit"))

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-0.8422  -0.8422  -0.8422   1.5548   1.9710  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.85394    0.03328 -25.656  &lt; 2e-16 ***
hrt         -0.93365    0.17405  -5.364 8.12e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5519.7  on 4588  degrees of freedom
Residual deviance: 5484.8  on 4587  degrees of freedom
AIC: 5488.8

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Because of the presence of the link function, we have two types of fitted values. The first, correspond to the log-odds scale and are stored in the <code>linear.predictors</code> vector of the regression object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(regr.hrt)</span>
<span id="cb4-2"><a href="#cb4-2"></a>y.hat <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(X <span class="sc">%*%</span> <span class="fu">coef</span>(regr.hrt)) <span class="co"># turn a 1-column matrix into a vector</span></span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="fu">all</span>(y.hat<span class="sc">==</span>regr.hrt<span class="sc">$</span>linear.predictors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>The second fitted values object correspond to the probability scale (the response scale), that is by transforming the linear predictors through the logistic function: these are stored in the <code>fitted.values</code> vector of the regression object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>logistic <span class="ot">&lt;-</span> <span class="cf">function</span>(z)<span class="fu">exp</span>(z)<span class="sc">/</span>(<span class="fu">exp</span>(z)<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb6-2"><a href="#cb6-2"></a>prob.case <span class="ot">&lt;-</span> <span class="fu">logistic</span>(regr.hrt<span class="sc">$</span>linear.predictors) </span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="fu">all</span>(prob.case <span class="sc">==</span> regr.hrt<span class="sc">$</span>fitted.values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>It is crucial not to mix the two scales, otherwise the interpretation will be affected.</p>
<p>In logistic regression the Wald test statistic is distributed according to a normal distribution because the standard deviation of the outcome does not need to be estimated (this is what the message <code>Dispersion parameter for binomial family taken to be 1</code> refers to). Therefore, the test statistic is now labelled <code>z value</code> (instead of t value). The p-value is obtained by comparing the test statistic to the quantiles of a standard normal distribution.</p>
<p>Recalling that <span class="math inline">\(ln(p/1-p) = X\beta\)</span> the estimated coefficients indicate how much the log-odds increase with each unit increase of the predictor. The sign of the regression coefficient tells us that the use of HRT has a protective effect on hip fractures (it reduces their odds). However, we need to transform it to an odds ratio in order to better appreciate the magnitude of the effect.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># exponentiate to get the odds ratio</span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="fu">exp</span>(<span class="fu">coef</span>(regr.hrt)[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      hrt 
0.3931169 </code></pre>
</div>
</div>
<p>If HRT had no effect, the odds ratio would be <span class="math inline">\(1\)</span>. An odds ratio of <span class="math inline">\(0.393\)</span> indicates that HRT reduces the odds of having a hip fracture by <span class="math inline">\(60.7\%\)</span>.To build a <span class="math inline">\(95\%\)</span> confidence interval on the odds ratio, we can rely on a normal approximation remembering that <span class="math inline">\(95\%\)</span> of the probability mass of a standard normal distribution is within <span class="math inline">\(-1.96\)</span> and <span class="math inline">\(1.96\)</span>, <span class="math inline">\(\exp({\hat{\beta}_i}±1.96×SE(\hat{\beta}_i))\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>beta <span class="ot">&lt;-</span> regr.hrt<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb10-2"><a href="#cb10-2"></a>se.beta <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(regr.hrt))[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="fu">round</span>(<span class="fu">exp</span>(beta<span class="fl">+1.96</span><span class="sc">*</span>se.beta<span class="sc">*</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.279 0.553</code></pre>
</div>
</div>
<p>Equivalently, it is possible to use the <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code> function. Results are not exactly the same, as the computation used above is based on asymptotic normality, while <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code> uses a t-distribution, which is usually better, especially for smaller sample sizes. Again, the intervals are in the log-odds scale, but we are interested in confidence intervals for the odds ratios, so we exponentiate them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>or.ci <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">confint</span>(regr.hrt)), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>or.ci</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            2.5 % 97.5 %
(Intercept) 0.399  0.454
hrt         0.276  0.546</code></pre>
</div>
</div>
<p>The confidence interval does not include <span class="math inline">\(1\)</span> (the odds ratio corresponding to no effect), so we can reject the null hypothesis of no effect for HRT.</p>
<p>The estimated intercept is <span class="math inline">\(-0.854\)</span>. Transforming the log-odds through the logistic function, we can compute the baseline probability, that is the probability of an event when all other covariates (in our case, just taking HRT) are zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>baseline.odds <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(regr.hrt)[<span class="dv">1</span>])</span>
<span id="cb16-2"><a href="#cb16-2"></a>baseline.prob <span class="ot">&lt;-</span> baseline.odds<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>baseline.odds)</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="co"># logistic function</span></span>
<span id="cb16-4"><a href="#cb16-4"></a><span class="fu">round</span>(baseline.prob, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
      0.299 </code></pre>
</div>
</div>
<p>This tells us that a woman in the study who does not take HRT has <span class="math inline">\(29.9\%\)</span> probability of experiencing a hip-fracture. How does this probability change if a woman takes HRT?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>hrt.odds <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(regr.hrt)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(regr.hrt)[<span class="dv">2</span>])</span>
<span id="cb18-2"><a href="#cb18-2"></a>hrt.prob <span class="ot">&lt;-</span> hrt.odds<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>hrt.odds)<span class="co"># logistic function</span></span>
<span id="cb18-3"><a href="#cb18-3"></a><span class="fu">round</span>(hrt.prob, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
      0.143 </code></pre>
</div>
</div>
<p>Note that these probabilities do not represent the absolute risk for a generic woman aged <span class="math inline">\(50–81\)</span>, as the proportion of cases in a case-control study generally does not reflect the proportion in the general population.</p>
<section id="exercise-1.1" class="level3"><h3 class="anchored" data-anchor-id="exercise-1.1">Exercise 1.1</h3>
<p>Using the <code>chdagesex.csv</code> dataset from Learn, fit a logistic regression model to test the association between age and coronary heart disease (<code>model M1</code>). Fit an additional model (<code>model M2</code>) which also includes <code>sex</code> then compute the odds ratio for the predictors and the <span class="math inline">\(95\%\)</span> confidence interval for both models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># Enter code here.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a>chdage <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/chdagesex.csv"</span>)</span>
<span id="cb21-2"><a href="#cb21-2"></a></span>
<span id="cb21-3"><a href="#cb21-3"></a>fit.m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CHD <span class="sc">~</span> AGE, <span class="at">data =</span> chdage, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb21-4"><a href="#cb21-4"></a>or.age <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit.m1)[<span class="dv">2</span>])</span>
<span id="cb21-5"><a href="#cb21-5"></a>ci.age <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(fit.m1))[<span class="dv">2</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">round</span>(<span class="fu">c</span>(or.age, ci.age), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   AGE  2.5 % 97.5 % 
  1.06   1.04   1.09 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a>fit.m2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(CHD <span class="sc">~</span> AGE <span class="sc">+</span> SEX, <span class="at">data =</span> chdage, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb25-2"><a href="#cb25-2"></a></span>
<span id="cb25-3"><a href="#cb25-3"></a>or.age <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit.m2)[<span class="dv">2</span>])</span>
<span id="cb25-4"><a href="#cb25-4"></a>ci.age <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(fit.m2))[<span class="dv">2</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="fu">round</span>(<span class="fu">c</span>(or.age, ci.age), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   AGE  2.5 % 97.5 % 
  1.06   1.04   1.09 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a>or.sex <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit.m2)[<span class="dv">3</span>])</span>
<span id="cb29-2"><a href="#cb29-2"></a>ci.sex <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(fit.m2))[<span class="dv">3</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="fu">round</span>(<span class="fu">c</span>(or.sex, ci.sex), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  SEXM  2.5 % 97.5 % 
  2.62   1.34   5.32 </code></pre>
</div>
</div>
</section></section><section id="model-evaluation" class="level1"><h1>2. Model evaluation</h1>
<p>The log-likelihood of a fitted model can be extracted with function <code><a href="https://rdrr.io/r/stats/logLik.html">logLik()</a></code>: this also outputs the number of degrees of freedom, that is the number of parameters estimated by the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="fu">logLik</span>(regr.hrt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -2742.4 (df=2)</code></pre>
</div>
</div>
<p>The deviance of a model is minus twice the log-likelihood. This is what R labels <code>residual deviance</code> when using <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> over a logistic regression object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(regr.hrt)) <span class="co"># same as regr.hrt$deviance</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5484.799</code></pre>
</div>
</div>
<p>The null deviance, instead, is minus twice the log-likelihood of a model which only uses the intercept term and no other predictor. A null model reports the same predicted probabilities for all observations, corresponding to the proportion of cases in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a>null.model <span class="ot">&lt;-</span><span class="fu">glm</span>(y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">family =</span> <span class="st">"binomial"</span>) <span class="co"># only the intercept in the model</span></span>
<span id="cb37-2"><a href="#cb37-2"></a><span class="fu">head</span>(null.model<span class="sc">$</span>fitted.values) <span class="co"># same probabilities for all observations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6 
0.2891698 0.2891698 0.2891698 0.2891698 0.2891698 0.2891698 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="fu">sum</span>(y)<span class="sc">/</span> <span class="fu">length</span>(y) <span class="co"># proportion of cases</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2891698</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a><span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(null.model)) <span class="co"># same as regr$null.deviance</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5519.71</code></pre>
</div>
</div>
<p>Models with better fit have lower deviance. In our case, adding one parameter to the null model decreases the deviance from <span class="math inline">\(5519.71\)</span> to <span class="math inline">\(5484.8\)</span>. The difference between two deviances has a <span class="math inline">\(\chi2\)</span> distribution with degrees of freedom equal to the difference in parameters of the two models. Therefore we can use it as a test statistic and compute a p-value under the null hypothesis that there is no support for an additional term. If the p-value is smaller than the significance level then we reject the null hypothesis and claim that the larger model provides a significantly better fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="fu">pchisq</span>(regr.hrt<span class="sc">$</span>null.deviance <span class="sc">-</span> regr.hrt<span class="sc">$</span>deviance, <span class="at">df =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.451601e-09</code></pre>
</div>
</div>
<section id="exercise-2.1" class="level3"><h3 class="anchored" data-anchor-id="exercise-2.1">Exercise 2.1</h3>
<p>Perform a likelihood ratio test comparing <code>model M1</code> to <code>model M2</code> from <strong>Exercise 1.1</strong> and confirm that the addition of <code>sex</code> to the model is significant at <span class="math inline">\(0.05\)</span> by computing a p-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="co"># Enter code here.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a>pval <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(fit.m1<span class="sc">$</span>deviance <span class="sc">-</span> fit.m2<span class="sc">$</span>deviance, <span class="at">df=</span><span class="dv">1</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb46-2"><a href="#cb46-2"></a><span class="fu">signif</span>(pval, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0047</code></pre>
</div>
</div>
<p>The AIC is another quantity derived from the log-likelihood which is used in model comparison, as it also takes into account model complexity, the deviance of the model is penalised by twice the number of parameters estimated in the model (stored in the rank field of the regression object).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="dv">2</span> <span class="sc">*</span> regr.hrt<span class="sc">$</span>rank <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(regr.hrt))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5488.799</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>regr.hrt<span class="sc">$</span>aic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5488.799</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a><span class="fu">AIC</span>(null.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5521.71</code></pre>
</div>
</div>
<p>As for the deviance, the lower the AIC, the better the model. However, there is no formal test that can be applied when comparing the AICs of two models. Nonetheless it can be a very useful initial tool to consider inclusion of variables in a model when there is a large number of variables (we will look at this and other methodologies for large datasets in the next lab).</p>
<p>The <code>BIC</code> (see R documentation) applies a stronger penalty for the use of additional predictors: even so, in this case the proposed model is still better than the null model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="fu">log</span>(<span class="fu">length</span>(y)) <span class="sc">*</span> regr.hrt<span class="sc">$</span>rank <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(regr.hrt))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5501.662</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="fu">BIC</span>(regr.hrt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5501.662</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a><span class="fu">BIC</span>(null.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5528.141</code></pre>
</div>
</div>
</section></section><section id="making-predictions" class="level1"><h1>3. Making predictions</h1>
<p>Let us consider a dataset which relates to subarachnoid hemorrhage (SAH), which is part of the <code>pROC</code> package. <code>SAH</code> is a rare, potentially fatal, type of stroke caused by bleeding on the surface of the brain. The dataset contains a clinical assessment score <code>wfns</code> and a couple of biomarkers <code>s100b</code> and <code>ndka</code> taken at the time of hospitalisation. The patients were re-assessed <span class="math inline">\(6\)</span> months later and the outcome is recorded in the clinical score <code>gos6</code>, this has been further reduced to the binary <code>outcome</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a><span class="fu">data</span>(aSAH) <span class="co"># copy the dataset from the package into the workspace</span></span>
<span id="cb60-2"><a href="#cb60-2"></a><span class="fu">summary</span>(aSAH)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> gos6   outcome      gender        age       wfns       s100b      
 1:28   Good:72   Male  :42   Min.   :18.0   1:39   Min.   :0.030  
 2: 0   Poor:41   Female:71   1st Qu.:42.0   2:32   1st Qu.:0.090  
 3:13                         Median :51.0   3: 4   Median :0.140  
 4: 6                         Mean   :51.1   4:16   Mean   :0.247  
 5:66                         3rd Qu.:61.0   5:22   3rd Qu.:0.330  
                              Max.   :81.0          Max.   :2.070  
      ndka       
 Min.   :  3.01  
 1st Qu.:  9.01  
 Median : 12.22  
 Mean   : 19.66  
 3rd Qu.: 17.30  
 Max.   :419.19  </code></pre>
</div>
</div>
<p>Let us start by fitting a simple model containing only <code>age</code> and <code>gender</code> on the entire dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a>asah.all <span class="ot">&lt;-</span><span class="fu">glm</span>(outcome <span class="sc">~</span> age <span class="sc">+</span> gender, <span class="at">data =</span> aSAH, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb62-2"><a href="#cb62-2"></a><span class="fu">summary</span>(asah.all)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = outcome ~ age + gender, family = "binomial", data = aSAH)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.7067  -0.9242  -0.6886   1.1156   2.0369  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)  -2.18408    0.83173  -2.626  0.00864 **
age           0.04441    0.01627   2.730  0.00633 **
genderFemale -1.13288    0.44696  -2.535  0.01126 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 148.04  on 112  degrees of freedom
Residual deviance: 136.18  on 110  degrees of freedom
AIC: 142.18

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>The <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function allows us to use a fitted regression model to make a prediction. The function takes two main arguments: a fitted prediction object (the output of <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> or <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code>) and a dataframe (specified by option <code>newdata</code>) containing the covariate values for which we want to make a prediction of the outcome. By default, for a logistic regression model <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> will return the linear predictors, that is the log-odds. If we are interested in predicted probabilities, we need to specify <code>type="response"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a>y.linpred <span class="ot">&lt;-</span> <span class="fu">predict</span>(asah.all, <span class="at">newdata =</span> aSAH) <span class="co"># predict the data used for fitting</span></span>
<span id="cb64-2"><a href="#cb64-2"></a>y.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(asah.all, <span class="at">newdata =</span> aSAH, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb64-3"><a href="#cb64-3"></a></span>
<span id="cb64-4"><a href="#cb64-4"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(y.linpred, asah.all<span class="sc">$</span>linear.predictors, y.pred, asah.all<span class="sc">$</span>fitted.values))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     y.linpred asah.all.linear.predictors    y.pred asah.all.fitted.values
29 -1.45171649                -1.45171649 0.1897375              0.1897375
30 -1.67376963                -1.67376963 0.1579222              0.1579222
31 -1.45171649                -1.45171649 0.1897375              0.1897375
32 -2.11787590                -2.11787590 0.1073715              0.1073715
33 -1.45171649                -1.45171649 0.1897375              0.1897375
34 -0.05237372                -0.05237372 0.4869096              0.4869096</code></pre>
</div>
</div>
<p>Predicting the same data that was used for fitting is not very interesting this produces what is already available in the <code>linear.predictors</code> and <code>fitted.values</code> vectors of the regression object. Moreover if we tried to use this to assess the predictive performance of the model, we would be overestimating it as it may be influenced by artefacts unique to his dataset. However this function is useful for predicting the outcome for new data.</p>
<p>This needs to be a dataframe containing columns that correspond to the predictors used in the model. For example, to predict the response for a <span class="math inline">\(30\)</span> years old male patient, we could create a dataframe to contain these data and ask the model to make a prediction for it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a>data<span class="fl">.30</span>M <span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">age=</span><span class="dv">30</span>, <span class="at">gender =</span> <span class="st">"Male"</span>)</span>
<span id="cb66-2"><a href="#cb66-2"></a><span class="fu">predict</span>(asah.all, <span class="at">newdata=</span>data<span class="fl">.30</span>M, <span class="at">type=</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.2990627 </code></pre>
</div>
</div>
<p>In general, predictions will be made on dataframes coming from different cohorts, or for subsets of the original dataset that were withdrawn, as in a cross-validation setting.</p>
<section id="exercise-3.1" class="level3"><h3 class="anchored" data-anchor-id="exercise-3.1">Exercise 3.1</h3>
<p>Create dataframe <code>agesex</code> containing two columns:</p>
<ul>
<li>
<code>AGE</code> with values in the sequence from <span class="math inline">\(1\)</span> to <span class="math inline">\(100\)</span>
</li>
<li>
<code>SEX</code> created as follows</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb68-2"><a href="#cb68-2"></a>SEX <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rbinom</span>(<span class="dv">100</span>, <span class="dv">1</span>, <span class="fl">0.5</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"F"</span>, <span class="st">"M"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Predict the probabilities of <code>CHD</code> for the <code>agesex</code> data according to <code>model M2</code> and plot them using a different colour according to sex.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1"></a><span class="co"># Enter code here.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a>agesex <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">AGE =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, SEX)</span>
<span id="cb70-2"><a href="#cb70-2"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit.m2, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">newdata =</span> agesex)</span>
<span id="cb70-3"><a href="#cb70-3"></a><span class="fu">plot</span>(agesex<span class="sc">$</span>AGE, pred, <span class="at">xlab =</span> <span class="st">"Age"</span>, </span>
<span id="cb70-4"><a href="#cb70-4"></a>     <span class="at">ylab =</span> <span class="st">"Predicted probability of CHD"</span>, <span class="at">col =</span> agesex<span class="sc">$</span>SEX)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Lab_3_Logistic_Regression_and_Predictive_Models_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section><section id="roc-curves" class="level2"><h2 class="anchored" data-anchor-id="roc-curves">3.1 ROC curves</h2>
<p>A common method to evaluate the ability of a model to predict binary outcomes is the use of <strong>Receiver operating characteristic (ROC)</strong> curves. Let us imagine that the output of some linear predictor ranges between zero and ten. If we say that all predicted values greater than zero are cases then our test will be correctly classifying all the observed cases and have a specificity of <span class="math inline">\(1\)</span>. However, all our controls will also have been wrongly classified as cases and our specificity is therefore zero.</p>
<p>Similarly, if we say that all predicted greater than ten are cases we would have a sensitivity of <span class="math inline">\(0\)</span> and a specificity of <span class="math inline">\(1\)</span>. ROC curves plot the sensitivity of a test against its specificity across all threshold values.</p>
<section id="exercise-3.2" class="level3"><h3 class="anchored" data-anchor-id="exercise-3.2">Exercise 3.2</h3>
<p>Using the <code>hemophilia.csv</code> dataset from Learn:</p>
<ul>
<li>Using <code><a href="https://rdrr.io/r/base/factor.html">as.factor()</a></code> and <code><a href="https://rdrr.io/r/base/integer.html">as.integer()</a></code>, convert the <code>group</code> variable to a <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span> integer variable to be used as outcome variable of a classification model. Use a logistic regression to model the probability of being a carrier of hemophilia A using the two <code>AHF</code> variables as predictors, call it <code>regr.hem</code> and retrieve the predicted probabilities.</li>
<li>Using a classification threshold <span class="math inline">\(\theta=0.5\)</span>, count the number of misclassified observations, the answer should be <span class="math inline">\(9\)</span>. Derive the sensitivity and specificity at this threshold.</li>
<li>Write a function called <code>sens.spec(y.obs, y.pred, threshold)</code> that computes sensitivity and specificity from a <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span> vector of observed outcomes, a vector of probabilities and a threshold value, and returns the two quantities as a vector.</li>
<li>Use the new function <code>sens.spec()</code> to compute sensitivity and specificity of <code>regr.hem</code> for at least <span class="math inline">\(10\)</span> equally-spaced values of <span class="math inline">\(\theta\)</span> spread in the interval <span class="math inline">\((0,1)\)</span> and use these to plot the ROC curve for <code>regr.hem</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1"></a><span class="co"># Enter code here.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1"></a>hemo <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/hemophilia.csv"</span>)</span>
<span id="cb72-2"><a href="#cb72-2"></a></span>
<span id="cb72-3"><a href="#cb72-3"></a><span class="fu">summary</span>(hemo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  AHFactivity        AHFantigen          group          
 Min.   :-0.6911   Min.   :-0.47730   Length:75         
 1st Qu.:-0.3609   1st Qu.:-0.12110   Class :character  
 Median :-0.2015   Median :-0.04070   Mode  :character  
 Mean   :-0.2387   Mean   :-0.03474                     
 3rd Qu.:-0.1176   3rd Qu.: 0.07520                     
 Max.   : 0.1507   Max.   : 0.28760                     </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1"></a>hemo<span class="sc">$</span>group <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">-</span> <span class="fu">as.integer</span>(<span class="fu">as.factor</span>(hemo<span class="sc">$</span>group)) <span class="co"># assign a 1 to carriers</span></span>
<span id="cb74-2"><a href="#cb74-2"></a></span>
<span id="cb74-3"><a href="#cb74-3"></a>regr.hem <span class="ot">&lt;-</span> <span class="fu">glm</span>(group <span class="sc">~</span> AHFantigen <span class="sc">+</span> AHFactivity, <span class="at">data =</span> hemo,</span>
<span id="cb74-4"><a href="#cb74-4"></a>                <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb74-5"><a href="#cb74-5"></a>probs <span class="ot">&lt;-</span> regr.hem<span class="sc">$</span>fitted.values</span>
<span id="cb74-6"><a href="#cb74-6"></a></span>
<span id="cb74-7"><a href="#cb74-7"></a>pred.case <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(probs <span class="sc">&gt;</span> <span class="fl">0.5</span>)</span>
<span id="cb74-8"><a href="#cb74-8"></a><span class="fu">sum</span>(pred.case <span class="sc">!=</span> hemo<span class="sc">$</span>group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1"></a>sens <span class="ot">&lt;-</span> <span class="fu">sum</span>(hemo<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> pred.case <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="fu">sum</span>(hemo<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb76-2"><a href="#cb76-2"></a><span class="fu">round</span>(sens, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.91</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1"></a>spec <span class="ot">&lt;-</span> <span class="fu">sum</span>(hemo<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> pred.case <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(hemo<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb78-2"><a href="#cb78-2"></a><span class="fu">round</span>(spec, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.83</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1"></a>sens.spec <span class="ot">&lt;-</span> <span class="cf">function</span>(threshold, y.obs, y.pred) {</span>
<span id="cb80-2"><a href="#cb80-2"></a>  sens <span class="ot">&lt;-</span> <span class="fu">sum</span>(y.obs <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> (y.pred <span class="sc">&gt;</span> threshold) <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="fu">sum</span>(y.obs <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb80-3"><a href="#cb80-3"></a>  spec <span class="ot">&lt;-</span> <span class="fu">sum</span>(y.obs <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> (y.pred <span class="sc">&gt;</span> threshold) <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(y.obs <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb80-4"><a href="#cb80-4"></a>  <span class="fu">return</span>(<span class="fu">c</span>(spec, sens))</span>
<span id="cb80-5"><a href="#cb80-5"></a>}</span>
<span id="cb80-6"><a href="#cb80-6"></a></span>
<span id="cb80-7"><a href="#cb80-7"></a>thresh <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by=</span><span class="fl">0.1</span>)</span>
<span id="cb80-8"><a href="#cb80-8"></a>ss <span class="ot">&lt;-</span> <span class="fu">sapply</span>(thresh, sens.spec, <span class="at">y.obs =</span> hemo<span class="sc">$</span>group, <span class="at">y.pred =</span> probs)</span>
<span id="cb80-9"><a href="#cb80-9"></a></span>
<span id="cb80-10"><a href="#cb80-10"></a><span class="fu">plot</span>(ss[<span class="dv">1</span>,], ss[<span class="dv">2</span>, ], <span class="at">xlab=</span><span class="st">"Specificity"</span>, <span class="at">ylab=</span><span class="st">"Sensitivity"</span>, <span class="at">type=</span><span class="st">"b"</span>) <span class="co"># plots points and joining them with lines</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Lab_3_Logistic_Regression_and_Predictive_Models_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A useful feature of the ROC curve is the fact that the <strong>Area Under the Curve (AUC)</strong> gives the overall probability of correctly ranking a randomly chosen case above a randomly chosen control. If our model was completely random we would have an equal chance of ranking either the randomly chosen case or the randomly chosen control above the other and the AUC would therefore be <span class="math inline">\(0.5\)</span>. To compute the AUC we can use the package <code>pROC</code>. This provides function <code>roc()</code>, which by default reports the area under curve, but offers an option to plot the entire ROC curve (see <code>?roc</code> for full documentation).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1"></a><span class="fu">roc</span>(hemo<span class="sc">$</span>group, regr.hem<span class="sc">$</span>fitted.values , <span class="at">plot=</span><span class="cn">TRUE</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">silent =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Lab_3_Logistic_Regression_and_Predictive_Models_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
roc.default(response = hemo$group, predictor = regr.hem$fitted.values,     plot = TRUE, xlim = c(0, 1), silent = TRUE)

Data: regr.hem$fitted.values in 30 controls (hemo$group 0) &lt; 45 cases (hemo$group 1).
Area under the curve: 0.96</code></pre>
</div>
</div>
<p><strong>NOTE</strong> wrapping <code>roc()</code> function with <code>suppressMessages(invisible())</code> will mute <code>Call()</code> output of the function. Thus, it will be cleaner as shown below</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab_3_Logistic_Regression_and_Predictive_Models_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let us look again at the HRT model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1"></a><span class="fu">suppressMessages</span>(<span class="fu">invisible</span>(</span>
<span id="cb85-2"><a href="#cb85-2"></a>  <span class="fu">roc</span>(y, regr.hrt<span class="sc">$</span>fitted.values, <span class="at">plot =</span> <span class="cn">TRUE</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb85-3"><a href="#cb85-3"></a>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Lab_3_Logistic_Regression_and_Predictive_Models_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>An AUC of <span class="math inline">\(0.52\)</span> is not good, this model is not very different from a random model at discriminating cases from controls. This model could help us understand if HRT has an effect on the odds of hip fractures but not to explain hip fractures based on HRT (or indeed to predict them!).</p>
</section><section id="exercise-3.3" class="level3"><h3 class="anchored" data-anchor-id="exercise-3.3">Exercise 3.3</h3>
<p>Plot the ROC curves for <code>model M1</code> and <code>model M2</code> in the same graph (hint: use option <code>add=TRUE</code> for the second curve) and report their AUCs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1"></a><span class="co"># Enter code here.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1"></a><span class="fu">suppressMessages</span>(<span class="fu">invisible</span>({</span>
<span id="cb87-2"><a href="#cb87-2"></a>  <span class="fu">roc</span>(chdage<span class="sc">$</span>CHD, fit.m1<span class="sc">$</span>fitted.values, <span class="at">plot =</span> <span class="cn">TRUE</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb87-3"><a href="#cb87-3"></a>  <span class="fu">roc</span>(chdage<span class="sc">$</span>CHD, fit.m2<span class="sc">$</span>fitted.values, <span class="at">plot =</span> <span class="cn">TRUE</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), </span>
<span id="cb87-4"><a href="#cb87-4"></a>      <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>) </span>
<span id="cb87-5"><a href="#cb87-5"></a>}))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Lab_3_Logistic_Regression_and_Predictive_Models_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section></section><section id="data-partitioning-and-cross-validation" class="level2"><h2 class="anchored" data-anchor-id="data-partitioning-and-cross-validation">3.2 Data partitioning and cross-validation</h2>
<p>Some convenient functions related to predictive models are implemented in the <code>caret</code> package.</p>
<p>This allows us to call function <code>createDataPartition()</code> which creates a single training/test split. This function (like similar ones in the same package) requires us to pass the vector of outcomes, so that the partition will contain a balanced proportion of cases and controls in the training and test sets. Before creating the partition, we must set the seed of the random number generation, so that results will be reproducible.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb88-2"><a href="#cb88-2"></a>train.idx <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(aSAH<span class="sc">$</span>outcome, <span class="at">p =</span> <span class="fl">0.7</span>)<span class="sc">$</span>Resample1 <span class="co"># 70-30 split</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This creates a list of indices corresponding to the observations in the training set. We can use this to fit the model only on this subset of data. The subset option of <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> and <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> allows control of the observations that are used to fit the model coefficients without making us create new dataframes to store the subsets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1"></a>asah.train <span class="ot">&lt;-</span> <span class="fu">glm</span>(outcome <span class="sc">~</span> age <span class="sc">+</span> gender, <span class="at">data =</span> aSAH, <span class="at">subset =</span> train.idx,</span>
<span id="cb89-2"><a href="#cb89-2"></a>                  <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb89-3"><a href="#cb89-3"></a></span>
<span id="cb89-4"><a href="#cb89-4"></a><span class="fu">summary</span>(asah.train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = outcome ~ age + gender, family = "binomial", data = aSAH, 
    subset = train.idx)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.3275  -0.9313  -0.7877   1.2344   1.8579  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  -1.66480    0.97556  -1.707   0.0879 .
age           0.03142    0.01930   1.628   0.1035  
genderFemale -0.83906    0.53474  -1.569   0.1166  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 104.77  on 79  degrees of freedom
Residual deviance: 100.84  on 77  degrees of freedom
AIC: 106.84

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Having fitted the same model on just a part of the data, we can see that the coefficients are different from those we obtained when we used all the data. Also p-values are less extreme, but this is mainly due to the reduced size of the dataset and the consequent increase in the standard errors. Note that we cannot use the deviance or the AIC to compare models fitted on different datasets (or, as in this case, on datasets of different sizes).</p>
<p>These quantities depend on the number of observations used in fitting, so a model fitted to a larger dataset will in general have higher deviance and AIC, but this is not necessarily an indication of bad quality of fit. What really matters is how well we predict the outcome for the withdrawn observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1"></a>pred.prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(asah.train, <span class="at">newdata =</span> aSAH[<span class="sc">-</span>train.idx, ],</span>
<span id="cb91-2"><a href="#cb91-2"></a>                     <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s plot the ROC curve for the prediction of the test data and compute the corresponding test AUC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1"></a><span class="fu">suppressMessages</span>(<span class="fu">invisible</span>(</span>
<span id="cb92-2"><a href="#cb92-2"></a>  <span class="fu">roc</span>(outcome <span class="sc">~</span> pred.prob, <span class="at">data =</span> aSAH[<span class="sc">-</span>train.idx, ], </span>
<span id="cb92-3"><a href="#cb92-3"></a>    <span class="at">plot =</span> <span class="cn">TRUE</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb92-4"><a href="#cb92-4"></a>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Lab_3_Logistic_Regression_and_Predictive_Models_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The AUC for this model <span class="math inline">\(0.8194\)</span> is quite good. Unfortunately, given that we created only one partition, it is hard to tell if a similar performance would be obtained on a different random training/test split. K-folds cross-validation essentially repeats this process for k different subsets and allows us to make a prediction for all observations of the dataset. The folds can be generated with the function <code>createFolds()</code>. By default the function returns a list of indices corresponding to the test set of each fold.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb93-2"><a href="#cb93-2"></a>num.folds <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb93-3"><a href="#cb93-3"></a>folds <span class="ot">&lt;-</span> <span class="fu">createFolds</span>(aSAH<span class="sc">$</span>outcome, <span class="at">k =</span> num.folds) <span class="co"># get indices of the test sets</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that the folds object is a list, this datatype allows to store different classes of objects (say vectors and dataframes) within the same variable. To access an element of a list, use the <code>[[]]</code> operator.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1"></a>folds[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]   2  10  11  12  13  29  37  48  59  91 107</code></pre>
</div>
</div>
<p>Now it is a matter of fitting a model in each of the training sets and predict the outcome for observations in the corresponding test sets. We need to store each fitted model so that they can be used afterwards for prediction or inspection: by assigning the output from <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> to <code>res.folds[[fold]]</code> we are effectively adding an element to a list of results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1"></a>regr.cv <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb96-2"><a href="#cb96-2"></a><span class="cf">for</span>(f <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num.folds) {</span>
<span id="cb96-3"><a href="#cb96-3"></a>  train.idx <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(aSAH), folds[[f]])</span>
<span id="cb96-4"><a href="#cb96-4"></a>  regr.cv[[f]] <span class="ot">&lt;-</span> <span class="fu">glm</span>(outcome <span class="sc">~</span> age <span class="sc">+</span> gender, <span class="at">data =</span> aSAH, </span>
<span id="cb96-5"><a href="#cb96-5"></a>                      <span class="at">subset =</span> train.idx, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb96-6"><a href="#cb96-6"></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exercise-3.4" class="level3"><h3 class="anchored" data-anchor-id="exercise-3.4">Exercise 3.4</h3>
<p>Write function <code>glm.cv(formula, data, folds)</code> that given:</p>
<ul>
<li>a model formula (an expression of the type <code>outcome ~ predictors</code>),</li>
<li>a dataframe containing outcome and predictors,</li>
<li>and a set of cross-validation folds produced by <code>createFolds()</code>, fits a logistic regression model in each of the folds and returns a list of fitted models.</li>
</ul>
<p>After setting the <code>set.seed(1)</code>, generate a set of <span class="math inline">\(10\)</span> cross-validation folds and use <code>glm.cv()</code> to cross-validate <code>model M1</code> and <code>model M2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1"></a><span class="co"># Enter code here.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1"></a>glm.cv <span class="ot">&lt;-</span> <span class="cf">function</span>(formula, data, folds) {</span>
<span id="cb98-2"><a href="#cb98-2"></a>  regr.cv <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb98-3"><a href="#cb98-3"></a>  <span class="cf">for</span> (f <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(folds)) {</span>
<span id="cb98-4"><a href="#cb98-4"></a>    regr.cv[[f]] <span class="ot">&lt;-</span> <span class="fu">glm</span>(formula, <span class="at">data=</span>data[<span class="sc">-</span>folds[[f]], ], <span class="at">family=</span><span class="st">"binomial"</span>)</span>
<span id="cb98-5"><a href="#cb98-5"></a>  }</span>
<span id="cb98-6"><a href="#cb98-6"></a>  <span class="fu">return</span>(regr.cv)</span>
<span id="cb98-7"><a href="#cb98-7"></a>}</span>
<span id="cb98-8"><a href="#cb98-8"></a></span>
<span id="cb98-9"><a href="#cb98-9"></a><span class="fu">set.seed</span>(<span class="dv">1675</span>) <span class="co"># Canged the seed as by chance it created a fold with no cases</span></span>
<span id="cb98-10"><a href="#cb98-10"></a>folds <span class="ot">&lt;-</span> <span class="fu">createFolds</span>(chdage<span class="sc">$</span>CHD, <span class="at">k=</span><span class="dv">10</span>)</span>
<span id="cb98-11"><a href="#cb98-11"></a>cv.m1 <span class="ot">&lt;-</span> <span class="fu">glm.cv</span>(CHD <span class="sc">~</span> AGE, chdage, folds)</span>
<span id="cb98-12"><a href="#cb98-12"></a>cv.m2 <span class="ot">&lt;-</span> <span class="fu">glm.cv</span>(CHD <span class="sc">~</span> AGE <span class="sc">+</span> SEX, chdage, folds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will need another loop to produce the predicted responses for each fold. For convenience we create a dataframe to store the observed outcome and what we predict from the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1"></a>pred.cv <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb99-2"><a href="#cb99-2"></a>auc.cv <span class="ot">&lt;-</span> <span class="fu">numeric</span>(num.folds)</span>
<span id="cb99-3"><a href="#cb99-3"></a><span class="fu">suppressMessages</span>(<span class="fu">invisible</span>({</span>
<span id="cb99-4"><a href="#cb99-4"></a>  <span class="cf">for</span>(f <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num.folds) {</span>
<span id="cb99-5"><a href="#cb99-5"></a>    test.idx <span class="ot">&lt;-</span> folds[[f]] </span>
<span id="cb99-6"><a href="#cb99-6"></a>    pred.cv[[f]] <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">obs =</span> aSAH<span class="sc">$</span>outcome[test.idx],</span>
<span id="cb99-7"><a href="#cb99-7"></a>                               <span class="at">pred =</span> <span class="fu">predict</span>(regr.cv[[f]], <span class="at">newdata =</span> aSAH,</span>
<span id="cb99-8"><a href="#cb99-8"></a>                                              <span class="at">type =</span> <span class="st">"response"</span>)[test.idx])</span>
<span id="cb99-9"><a href="#cb99-9"></a>    auc.cv[f] <span class="ot">&lt;-</span> <span class="fu">roc</span>(obs <span class="sc">~</span> pred, <span class="at">data =</span> pred.cv[[f]])<span class="sc">$</span>auc</span>
<span id="cb99-10"><a href="#cb99-10"></a>  }  </span>
<span id="cb99-11"><a href="#cb99-11"></a>}))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After cross-validation, we can report the expected performance of the model on withdrawn data. This is slightly smaller than what we obtained when using a single partition, but we can attach more confidence to this estimate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(auc.cv), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.713</code></pre>
</div>
</div>
</section><section id="exercise-3.5" class="level3"><h3 class="anchored" data-anchor-id="exercise-3.5">Exercise 3.5</h3>
<p>Write function <code>predict.cv(regr.cv, data, outcome, folds)</code> where:</p>
<ul>
<li>
<code>regr.cv</code> is a list of fitted models produced by <code>glm.cv()</code>,</li>
<li>data is a dataframe of covariates,</li>
<li>outcome is the vector of observed outcomes,</li>
<li>and folds is the set of cross-validation folds. The function should use the model fitted on the training set of each fold to predict the outcome of the corresponding test set. The function should return a list of dataframes, each containing observed and predicted outcome for the test observations. Use <code>predict.cv()</code> to make predictions for both <code>model M1</code> and <code>model M2</code>. Using these predictions, compute AUCs for all folds and report the mean cross-validated AUCs.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1"></a><span class="co"># Enter code here.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1"></a>predict.cv <span class="ot">&lt;-</span> <span class="cf">function</span>(regr.cv, data, outcome, folds) {</span>
<span id="cb103-2"><a href="#cb103-2"></a>  pred.cv <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb103-3"><a href="#cb103-3"></a>  <span class="cf">for</span> (f <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(folds)) {</span>
<span id="cb103-4"><a href="#cb103-4"></a>    test.idx <span class="ot">&lt;-</span> folds[[f]]</span>
<span id="cb103-5"><a href="#cb103-5"></a>    pred.cv[[f]] <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">obs =</span> outcome[test.idx],</span>
<span id="cb103-6"><a href="#cb103-6"></a>                              <span class="at">pred =</span> <span class="fu">predict</span>(regr.cv[[f]], </span>
<span id="cb103-7"><a href="#cb103-7"></a>                              <span class="at">newdata =</span> data[test.idx,],</span>
<span id="cb103-8"><a href="#cb103-8"></a>                              <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb103-9"><a href="#cb103-9"></a>  }</span>
<span id="cb103-10"><a href="#cb103-10"></a>  <span class="fu">return</span>(pred.cv)</span>
<span id="cb103-11"><a href="#cb103-11"></a>}</span>
<span id="cb103-12"><a href="#cb103-12"></a></span>
<span id="cb103-13"><a href="#cb103-13"></a>pred.cv.m1 <span class="ot">&lt;-</span> <span class="fu">predict.cv</span>(cv.m1, chdage, chdage<span class="sc">$</span>CHD, folds)</span>
<span id="cb103-14"><a href="#cb103-14"></a>pred.cv.m2 <span class="ot">&lt;-</span> <span class="fu">predict.cv</span>(cv.m2, chdage, chdage<span class="sc">$</span>CHD, folds)</span>
<span id="cb103-15"><a href="#cb103-15"></a></span>
<span id="cb103-16"><a href="#cb103-16"></a>auc.cv.m1 <span class="ot">&lt;-</span> auc.cv.m2 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(folds))</span>
<span id="cb103-17"><a href="#cb103-17"></a></span>
<span id="cb103-18"><a href="#cb103-18"></a><span class="fu">suppressMessages</span>(<span class="fu">invisible</span>({</span>
<span id="cb103-19"><a href="#cb103-19"></a>  <span class="cf">for</span> (f <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(folds)) {</span>
<span id="cb103-20"><a href="#cb103-20"></a>    auc.cv.m1[f] <span class="ot">&lt;-</span> <span class="fu">roc</span>(obs <span class="sc">~</span> pred, <span class="at">data =</span> pred.cv.m1[[f]])<span class="sc">$</span>auc</span>
<span id="cb103-21"><a href="#cb103-21"></a>    auc.cv.m2[f] <span class="ot">&lt;-</span> <span class="fu">roc</span>(obs <span class="sc">~</span> pred, <span class="at">data =</span> pred.cv.m2[[f]])<span class="sc">$</span>auc</span>
<span id="cb103-22"><a href="#cb103-22"></a>  }</span>
<span id="cb103-23"><a href="#cb103-23"></a>}))</span>
<span id="cb103-24"><a href="#cb103-24"></a></span>
<span id="cb103-25"><a href="#cb103-25"></a><span class="fu">round</span>(<span class="fu">mean</span>(auc.cv.m1), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.744</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(auc.cv.m2), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.744</code></pre>
</div>
</div>
</section><section id="exercise-3.6" class="level3"><h3 class="anchored" data-anchor-id="exercise-3.6">Exercise 3.6</h3>
<p>Consider the following summary statistics from a study of smoking in students:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">student_smokes =</span> <span class="fu">c</span>(<span class="dv">816</span>, <span class="dv">188</span>),</span>
<span id="cb107-2"><a href="#cb107-2"></a>           <span class="at">student_nosmokes =</span> <span class="fu">c</span>(<span class="dv">3203</span>, <span class="dv">1168</span>))</span>
<span id="cb107-3"><a href="#cb107-3"></a><span class="fu">rownames</span>(df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"at least one parent smokes"</span>, <span class="st">"neither parent smokes"</span>)</span>
<span id="cb107-4"><a href="#cb107-4"></a><span class="fu">kable</span>(df, <span class="at">caption =</span> <span class="st">"Study of Smoking in students"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb107-5"><a href="#cb107-5"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> F, <span class="at">position =</span> <span class="st">"center"</span>, <span class="at">latex_options =</span> <span class="st">"hold_position"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Study of Smoking in students</caption>
 <thead><tr>
<th style="text-align:left;">   </th>
   <th style="text-align:right;"> student_smokes </th>
   <th style="text-align:right;"> student_nosmokes </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:left;"> at least one parent smokes </td>
   <td style="text-align:right;"> 816 </td>
   <td style="text-align:right;"> 3203 </td>
  </tr>
<tr>
<td style="text-align:left;"> neither parent smokes </td>
   <td style="text-align:right;"> 188 </td>
   <td style="text-align:right;"> 1168 </td>
  </tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>Compute the odds ratio of smoking in students according to the exposure to smoking in parents directly from the values in the table.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1"></a><span class="fu">round</span>((<span class="dv">816</span><span class="sc">/</span><span class="dv">188</span>) <span class="sc">/</span> (<span class="dv">3203</span><span class="sc">/</span><span class="dv">1168</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.58</code></pre>
</div>
</div>
<ul>
<li>Create a synthetic dataset with the same characteristics as those in the table and fit a logistic regression model to it. Check that the odds ratio for exposure to smoking in parents matches what you computed before and report the <span class="math inline">\(95\%\)</span> confidence interval, and the Wald test p-value.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1"></a>par.smoke <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">816</span> <span class="sc">+</span> <span class="dv">3203</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">188</span> <span class="sc">+</span> <span class="dv">1168</span>))</span>
<span id="cb110-2"><a href="#cb110-2"></a>stu.smoke <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">816</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">3203</span>), <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">188</span>), <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">1168</span>))</span>
<span id="cb110-3"><a href="#cb110-3"></a></span>
<span id="cb110-4"><a href="#cb110-4"></a>regr.smoke <span class="ot">&lt;-</span> <span class="fu">glm</span>(stu.smoke <span class="sc">~</span> par.smoke, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb110-5"><a href="#cb110-5"></a></span>
<span id="cb110-6"><a href="#cb110-6"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(regr.smoke)[<span class="dv">2</span>]), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>par.smoke 
     1.58 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">confint</span>(regr.smoke)[<span class="dv">2</span>, ]), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> 2.5 % 97.5 % 
  1.34   1.88 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1"></a><span class="fu">signif</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(regr.smoke))[<span class="dv">2</span>, <span class="dv">4</span>], <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.71e-07</code></pre>
</div>
</div>
<ul>
<li>By using the deviance, test the goodness-of-fit of the model by deriving a p-value.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1"></a><span class="fu">signif</span>(<span class="fu">pchisq</span>(regr.smoke<span class="sc">$</span>null.deviance <span class="sc">-</span> regr.smoke<span class="sc">$</span>deviance, <span class="at">df =</span> <span class="dv">1</span>,</span>
<span id="cb117-2"><a href="#cb117-2"></a>              <span class="at">lower.tail =</span> <span class="cn">FALSE</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.8e-08</code></pre>
</div>
</div>
<ul>
<li>From the regression coefficients compute the probability of smoking for a student whose parents do not smoke and for a student whose parents smoke.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1"></a><span class="fu">predict</span>(regr.smoke, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">par.smoke =</span> <span class="dv">0</span>), <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.1386431 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1"></a><span class="fu">predict</span>(regr.smoke, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">par.smoke =</span> <span class="dv">1</span>), <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.2030356 </code></pre>
</div>
</div>
<ul>
<li>Compute the sensitivity and specificity of the model for threshold values of <span class="math inline">\(0.12\)</span>, <span class="math inline">\(0.14\)</span>, <span class="math inline">\(0.2\)</span> and <span class="math inline">\(0.22\)</span>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1"></a><span class="cf">for</span> (theta <span class="cf">in</span> <span class="fu">c</span>(<span class="fl">0.12</span>, <span class="fl">0.14</span>, <span class="fl">0.2</span>, <span class="fl">0.22</span>)){</span>
<span id="cb123-2"><a href="#cb123-2"></a>  sens <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">fitted</span>(regr.smoke) <span class="sc">&gt;</span> theta <span class="sc">&amp;</span> stu.smoke) <span class="sc">/</span> <span class="fu">sum</span>(stu.smoke)</span>
<span id="cb123-3"><a href="#cb123-3"></a>  </span>
<span id="cb123-4"><a href="#cb123-4"></a>  spec <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">fitted</span>(regr.smoke) <span class="sc">&lt;</span> theta <span class="sc">&amp;</span> (<span class="dv">1</span> <span class="sc">-</span> stu.smoke)) <span class="sc">/</span> <span class="fu">sum</span>(<span class="dv">1</span> <span class="sc">-</span> stu.smoke)</span>
<span id="cb123-5"><a href="#cb123-5"></a>  <span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">'Theta: '</span>, theta, <span class="st">', Sensitivity: '</span>, <span class="fu">round</span>(sens, <span class="dv">3</span>), <span class="st">', Specificity: '</span>, <span class="fu">round</span>(spec, <span class="dv">3</span>)))</span>
<span id="cb123-6"><a href="#cb123-6"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Theta: 0.12, Sensitivity: 1, Specificity: 0"
[1] "Theta: 0.14, Sensitivity: 0.813, Specificity: 0.267"
[1] "Theta: 0.2, Sensitivity: 0.813, Specificity: 0.267"
[1] "Theta: 0.22, Sensitivity: 0, Specificity: 1"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1"></a><span class="co"># Enter code here.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section></section></main><!-- /main column --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>